Repository SkillsFundingAgency/das-assessor-service, pull requests merged in 2019-03, with the labels that each got.

#585 On 1506 add new organisation and contact
  src/SFA.DAS.AssessorService.Api.Types/Models/CreateOrganisationContactRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/CreateOrganisationContactResponse.cs
  src/SFA.DAS.AssessorService.Application.Api.UnitTests/Services/AssessorValidationServiceTests.cs
  src/SFA.DAS.AssessorService.Application.Api.UnitTests/Services/ValidationServiceTests.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/RegisterController.cs
  src/SFA.DAS.AssessorService.Application.Api/Services/Validation/AssessorValidationService.cs
  src/SFA.DAS.AssessorService.Application.Api/Services/Validation/EmailCheck.cs
  src/SFA.DAS.AssessorService.Application.Api/Services/Validation/EmailCheckValidator.cs
  src/SFA.DAS.AssessorService.Application.Api/Services/Validation/ValidationService.cs
  src/SFA.DAS.AssessorService.Application/Handlers/EpaOrganisationHandlers/CreateEpaOrganisationContactHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/EpaOrganisationHandlers/CreateOrganisationAndContactHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Validation/ValidationHandler.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/IEpaOrganisationValidator.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/IRegisterValidationRepository.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/Validation/IAssessorValidationService.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/Validation/IValidationService.cs
  src/SFA.DAS.AssessorService.Application/Resources/OrganisationAndContactMessages.Designer.cs
  src/SFA.DAS.AssessorService.Application/Resources/OrganisationAndContactMessages.resx
  src/SFA.DAS.AssessorService.Application/SFA.DAS.AssessorService.Application.csproj
  src/SFA.DAS.AssessorService.Data.IntegrationTests/EpaOrganisationValidatorTests.cs
  src/SFA.DAS.AssessorService.Data/RegisterValidationRepository.cs
Labels: Tested

#591 ON-1456 - Exempt Questions
  src/SFA.DAS.AssessorService.ApplyTypes/ApplicationSection.cs
  src/SFA.DAS.AssessorService.ApplyTypes/Page.cs
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/Apply/ApplicationController.cs
  src/SFA.DAS.AssessorService.Web.Staff/Views/Apply/Applications/Section.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Apply/Applications/Section_ReadOnly.cshtml
Labels: Tested

#595 On 1459 stop multiple form submit
  src/SFA.DAS.AssessorService.Web.Staff/Views/Apply/Applications/Assessment.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Apply/Applications/Page.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Apply/Applications/Section.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Apply/Applications/Sequence.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Apply/Financial/Application.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/wwwroot/js/site.js
Labels: Tested

#603 ON-1484 Removed UKPRN (Training Provider) from Pipeline dashboard and .CSV extract. Updated EPAO Pipelines query for to remove Training Provider and performance.
  src/SFA.DAS.AssessorService.Api.Types/EpaoPipelineStandardsResponse.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Standards/GetEpaoPipelineStandardsHandler.cs
  src/SFA.DAS.AssessorService.Database/StoredProcedures/GetEPAO_Pipelines.sql
  src/SFA.DAS.AssessorService.Web/Controllers/OrganisationStandardsController.cs
  src/SFA.DAS.AssessorService.Web/Views/OrganisationStandards/Pipelines.cshtml
Labels: Tested

#608 ON-1635 - 'Remove' Feedback Banner Link
  src/SFA.DAS.AssessorService.Web.Staff/Views/Shared/_Layout.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Shared/_DashboardLayout.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Shared/_Layout.cshtml
Labels: Ready for Release, Tested

#604 Apr 233 add organisation validation
  src/SFA.DAS.AssessorService.Api.Types/Models/Roatp/DuplicateCharityNumberCheckRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/Roatp/DuplicateCheckResponse.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/Roatp/DuplicateCompanyNumberCheckRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/Roatp/DuplicateUKPRNCheckRequest.cs
  src/SFA.DAS.AssessorService.Web.Staff.Tests/Controllers/Roatp/AddRoatpOrganisationControllerTests.cs
  src/SFA.DAS.AssessorService.Web.Staff.Tests/SFA.DAS.AssessorService.Web.Staff.Tests.csproj
  src/SFA.DAS.AssessorService.Web.Staff.Tests/Validators/AddOrganisationValidatorTests.cs
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/Roatp/AddRoatpOrganisationController.cs
  src/SFA.DAS.AssessorService.Web.Staff/Infrastructure/IRoatpApiClient.cs
  src/SFA.DAS.AssessorService.Web.Staff/Infrastructure/IRoatpSessionService.cs
  src/SFA.DAS.AssessorService.Web.Staff/Infrastructure/RoatpApiClient.cs
  src/SFA.DAS.AssessorService.Web.Staff/Infrastructure/RoatpSessionService.cs
  src/SFA.DAS.AssessorService.Web.Staff/Resources/RoatpOrganisationValidation.Designer.cs
  src/SFA.DAS.AssessorService.Web.Staff/Resources/RoatpOrganisationValidation.resx
  src/SFA.DAS.AssessorService.Web.Staff/SFA.DAS.AssessorService.Web.Staff.csproj
  src/SFA.DAS.AssessorService.Web.Staff/Validators/Roatp/AddOrganisationProviderTypeViewModelValidator.cs
  src/SFA.DAS.AssessorService.Web.Staff/Validators/Roatp/AddOrganisationValidationErrorMessages.cs
  src/SFA.DAS.AssessorService.Web.Staff/Validators/Roatp/AddOrganisationValidator.cs
  src/SFA.DAS.AssessorService.Web.Staff/Validators/Roatp/AddOrganisationViewModelValidator.cs
  src/SFA.DAS.AssessorService.Web.Staff/Validators/Roatp/IAddOrganisationValidator.cs
  src/SFA.DAS.AssessorService.Web.Staff/ViewModels/Roatp/AddOrganisationViewModel.cs
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/AddOrganisation.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/AddOrganisationDetails.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/AddOrganisationPreview.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/_AddOrganisationValidationErrorsPartial.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/wwwroot/css/roatp.css
Labels: Ready for Release, RoATP, Tested

#612 Apr 166 roatp search
  src/SFA.DAS.AssessorService.Api.Types/Models/Roatp/OrganisationSearchResults.cs
  src/SFA.DAS.AssessorService.Web.Staff.Tests/Controllers/Roatp/AddRoatpOrganisationControllerTests.cs
  src/SFA.DAS.AssessorService.Web.Staff.Tests/Validators/AddOrganisationValidatorTests.cs
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/Roatp/AddRoatpOrganisationController.cs
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/Roatp/RoatpHomeController.cs
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/Roatp/RoatpSearchController.cs
  src/SFA.DAS.AssessorService.Web.Staff/Infrastructure/IRoatpApiClient.cs
  src/SFA.DAS.AssessorService.Web.Staff/Infrastructure/IRoatpSessionService.cs
  src/SFA.DAS.AssessorService.Web.Staff/Infrastructure/RoatpApiClient.cs
  src/SFA.DAS.AssessorService.Web.Staff/Infrastructure/RoatpSessionService.cs
  src/SFA.DAS.AssessorService.Web.Staff/Resources/RoatpSearchValidation.Designer.cs
  src/SFA.DAS.AssessorService.Web.Staff/Resources/RoatpSearchValidation.resx
  src/SFA.DAS.AssessorService.Web.Staff/SFA.DAS.AssessorService.Web.Staff.csproj
  src/SFA.DAS.AssessorService.Web.Staff/Validators/Roatp/AddOrganisationProviderTypeViewModelValidator.cs
  src/SFA.DAS.AssessorService.Web.Staff/Validators/Roatp/ISearchTermValidator.cs
  src/SFA.DAS.AssessorService.Web.Staff/Validators/Roatp/OrganisationSearchViewModelValidator.cs
  src/SFA.DAS.AssessorService.Web.Staff/Validators/Roatp/SearchTermValidator.cs
  src/SFA.DAS.AssessorService.Web.Staff/ViewModels/Roatp/OrganisationSearchResultsViewModel.cs
  src/SFA.DAS.AssessorService.Web.Staff/ViewModels/Roatp/OrganisationSearchViewModel.cs
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/Index.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/SearchResults.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/wwwroot/css/roatp.css
Labels: Ready for Release, Tested

#605 ON-1629 - Fixed Null Reference when Certificate exists but Ilr doesn't
  src/SFA.DAS.AssessorService.Data/Staff/StaffIlrRepository.cs
Labels: Ready for Release, Tested

#610 Apr 344 add organisation tech debt
  src/SFA.DAS.AssessorService.Api.Types/Models/Roatp/CreateOrganisationRequest.cs
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/Roatp/AddRoatpOrganisationController.cs
  src/SFA.DAS.AssessorService.Web.Staff/Infrastructure/IRoatpApiClient.cs
Labels: Ready for Release, RoATP, Tested
