Repository SkillsFundingAgency/das-assessor-service, pull requests merged in 2019-10, with the labels that each got.

#925 ON-2293 - Remove opening hours from contact page
  azure/template.json
  src/SFA.DAS.AssessorService.Web/Views/Shared/_ContactUsPartial.cshtml
Labels: Requires testing

#924 On 2091 aad feedback and review
  azure/template.json
  src/SFA.DAS.AssessorService.Api.Types/Consts/EmailTemplateNames.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/Apply/ApplicationResponse.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/Apply/Financial/Review/ReturnFinancialReviewRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/Apply/Financial/Review/StartFinancialReviewRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/Apply/Review/ClosedApplicationsRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/Apply/Review/EvaluateApplicationSectionRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/Apply/Review/FeedbackAddedApplicationsRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/Apply/Review/OpenApplicationsRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/Apply/Review/ReturnApplicationSequenceRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/Apply/Review/StartApplicationSectionReviewRequest.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/ApplicationReviewController.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/Apply/ApplicationController.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/Apply/ApplicationReviewController.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/Apply/FinancialController.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Apply/Financial/Review/ReturnFinancialReviewHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Apply/Financial/Review/StartFinancialReviewHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Apply/Financial/Review/UpdateGradeHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Apply/Review/ClosedApplicationsHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Apply/Review/EvaluateApplicationSectionHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Apply/Review/FeedbackAddedApplicationsHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Apply/Review/OpenApplicationsHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Apply/Review/ReturnApplicationHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Apply/Review/ReturnApplicationSequenceHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Apply/Review/StartApplicationSectionReviewHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Apply/SubmitApplicationHandler.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/IApplyRepository.cs
  src/SFA.DAS.AssessorService.ApplyTypes/ApplicationReviewStatus.cs
  src/SFA.DAS.AssessorService.ApplyTypes/ApplicationSequence.cs
  src/SFA.DAS.AssessorService.ApplyTypes/ApplicationStatus.cs
  src/SFA.DAS.AssessorService.ApplyTypes/ApplicationSummaryItem.cs
  src/SFA.DAS.AssessorService.ApplyTypes/FinancialApplicationSummaryItem.cs
  src/SFA.DAS.AssessorService.ApplyTypes/FinancialReviewStatus.cs
  src/SFA.DAS.AssessorService.Data/Apply/ApplyRepository.cs
  src/SFA.DAS.AssessorService.Database/SFA.DAS.AssessorService.Database.sqlproj
  src/SFA.DAS.AssessorService.Database/Views/ApplicationSummary.sql
  src/SFA.DAS.AssessorService.Web/Controllers/Apply/ApplicationController.cs
  src/SFA.DAS.AssessorService.Web/Infrastructure/NotEqualRouteContraint.cs
  src/SFA.DAS.AssessorService.Web/Startup.cs
Labels: Do not merge

#927 ON-2328 - Copy updates
  src/SFA.DAS.AssessorService.Web/Views/OppFinder/ApprovedDetails.cshtml
  src/SFA.DAS.AssessorService.Web/Views/OppFinder/Index.cshtml
  src/SFA.DAS.AssessorService.Web/Views/OppFinder/_InDevelopmentStandardsPartial.cshtml
  src/SFA.DAS.AssessorService.Web/Views/OppFinder/_ProposedStandardsPartial.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Shared/_OppFinderServiceLayout.cshtml
Labels: Requires testing

#929 ON-2151 Display the completion status for the learner
  src/SFA.DAS.AssessorService.Api.Types/Models/LearnerDetail.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Staff/LearnerDetailHandler.cs
  src/SFA.DAS.AssessorService.Web/Controllers/OrganisationController.cs
  src/SFA.DAS.AssessorService.Web/wwwroot/javascripts/govuk-postcode-lookup-service.min.js
Labels: Ready for Release, Tested

#932 ON-2253 Prevent pending users from receiving email notifications for manage users
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/EmailHandler/WhenSendOrganisationDetailsAmendedEmail.cs
  src/SFA.DAS.AssessorService.Application/Handlers/EmailHandlers/SendOrganisationDetailsAmendedEmailHandler.cs
Labels: Tested

#928 On 2287 Separation of users and contacts to support manage users in admin service
  src/SFA.DAS.AssessorService.Api.Types/Models/ContactIncludePrivilegesResponse.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/GetAllContactsIncludePrivilegesRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/GetAllContactsRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/GetContactsWithPrivilegesRequest.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/ContactsApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/IContactsApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/ContactQueryController.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/EmailHandler/WhenSendOrganisationDetailsAmendedEmail.cs
  src/SFA.DAS.AssessorService.Application/Handlers/ContactHandlers/GetAllContactsHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/ContactHandlers/GetAllContactsIncludePrivilegesHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/EmailHandlers/SendOrganisationDetailsAmendedEmailHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/UserManagement/NotifyUserManagementUsersHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/UserManagement/RemoveContactFromOrganisationHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/UserManagement/RequestForPrivilegeHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/UserManagement/SetContactPrivilegesHandler.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/IContactQueryRepository.cs
  src/SFA.DAS.AssessorService.Data/ContactQueryRepository.cs
  src/SFA.DAS.AssessorService.Domain/Entities/ContactLog.cs
  src/SFA.DAS.AssessorService.Web.UnitTests/OrganisationControllerTests/WhenPostSelectOrChangeContactNameConfirm.cs
  src/SFA.DAS.AssessorService.Web.UnitTests/OrganisationControllerTests/WhenPostSelectOrChangeContactNameSaveWithErrors.cs
  src/SFA.DAS.AssessorService.Web.UnitTests/OrganisationControllerTests/WhenPostSelectOrChangeContactNameSaveWithoutErrors.cs
  src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/ManageUsersController.cs
  src/SFA.DAS.AssessorService.Web/Views/ManageUsers/Index.cshtml
Labels: Tested

#940 ON 2335 Content changes for first application approved
  src/SFA.DAS.AssessorService.Web/Views/Home/NotActivated.cshtml
Labels: Tested

#939 ON 2282 Only record different epa outcome when certficate is submitted
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Certificates/UpdateCertificateHandlerTests/When_called_and_existing_certificate.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Certificates/UpdateCertificateHandlerTests/When_called_to_record_a_grade.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Certificates/UpdateCertificateHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/ExternalApi/Certificates/UpdateBatchCertificateHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Private/StartPrivateCertificateHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Staff/StartCertificateHandler.cs
Labels: Tested

#921 On 2310 allow epa os to submit requests for deleted records
  src/._SFA.DAS.AssessorService.sln
  src/SFA.DAS.AssessorService.Application/Handlers/Private/StartPrivateCertificateHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Search/SearchHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Staff/StartCertificateHandler.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/ICertificateRepository.cs
  src/SFA.DAS.AssessorService.Data/CertificateRepository.cs
  src/SFA.DAS.AssessorService.Web/Controllers/CertificateBaseController.cs
Labels: Tested

#941 ON 2265 Added a screen to confirm renewal of API key
  src/SFA.DAS.AssessorService.Application.Api.Client/Azure/AzureApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Azure/IAzureApiClient.cs
  src/SFA.DAS.AssessorService.Web/Controllers/OrganisationController.cs
  src/SFA.DAS.AssessorService.Web/Extensions/TagHelpers/AlertTagHelper.cs
  src/SFA.DAS.AssessorService.Web/Extensions/TempDataExtension.cs
  src/SFA.DAS.AssessorService.Web/Infrastructure/Alert.cs
  src/SFA.DAS.AssessorService.Web/SFA.DAS.AssessorService.Web.csproj
  src/SFA.DAS.AssessorService.Web/ViewModels/Organisation/RenewApiKeyViewModel.cs
  src/SFA.DAS.AssessorService.Web/Views/Organisation/OrganisationDetails.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Organisation/RenewApiKey.cshtml
  src/SFA.DAS.AssessorService.Web/wwwroot/stylesheets/application.css
Labels: Tested
