Repository SkillsFundingAgency/das-assessor-service, pull requests merged in 2019-09, with the labels that each got.

#884 ON-2249 - Learner details should be expecting a null certificate
  src/SFA.DAS.AssessorService.Api.Types/Models/LearnerDetail.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Staff/LearnerDetailHandler.cs
Labels: Tested

#831 On 2041 inconsistent status with pf certificates certificates log
  src/SFA.DAS.AssessorService.Data/CertificateRepository.cs
Labels: Tested

#876 ON-2033_anytime_updates_live_contacts_only
  src/SFA.DAS.AssessorService.Api.Types/Models/GetContactsWhoCanBePrimaryForOrganisationRequest.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/ContactsApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/IContactsApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/ContactQueryController.cs
  src/SFA.DAS.AssessorService.Application/Handlers/OrganisationHandlers/GetContactsWhoCanBePrimaryForOrganisationHandler.cs
  src/SFA.DAS.AssessorService.Web/Controllers/OrganisationController.cs
Labels: Tested

#883 Added healthcheck endpoint
  azure/sandbox-template.json
  azure/template.json
  src/SFA.DAS.AssessorService.Application.Api/StartupConfiguration/Startup.cs
  src/SFA.DAS.AssessorService.Web/Startup.cs
Labels: Ready for Release, Tested

#902 ON-2276_Add_grade_outstanding
  src/SFA.DAS.AssessorService.Application.Api.External/Controllers/CertificateController.cs
  src/SFA.DAS.AssessorService.Application.Api/Validators/ExternalApi/Certificates/BatchCertificateRequestValidator.cs
  src/SFA.DAS.AssessorService.Application/Handlers/ExternalApi/_HelperClasses/CertificateHelpers.cs
  src/SFA.DAS.AssessorService.Domain/Consts/CertificateGrade.cs
  src/SFA.DAS.AssessorService.Web/ViewModels/Certificate/CertificateGradeViewModel.cs
Labels: Ready for Release
