Repository SkillsFundingAgency/das-assessor-service, pull requests merged in 2019-07, with the labels that each got.

#814 Fixed lack of await on a db call that was causing an exception when t…
  src/SFA.DAS.AssessorService.Application/Handlers/Certificates/GetCertificatesToBeApprovedHandler.cs
Labels: Tested

#811 ON-1926 Not Setting Username From Unknown% To Real Value
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Login/LoginHandlerTestsBase.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Login/When_Contact_exists_and_username_is_now_known.cs
  src/SFA.DAS.AssessorService.Application/Handlers/EpaOrganisationHandlers/CreateEpaOrganisationContactHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Login/LoginHandler.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/IContactRepository.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/IRegisterRepository.cs
  src/SFA.DAS.AssessorService.Data/ContactRepository.cs
  src/SFA.DAS.AssessorService.Data/RegisterRepository.cs
  src/SFA.DAS.AssessorService.Database/Script.PostDeployment1.sql
Labels: Tested

#826 ON 2063 Content Changes To User Management
  src/SFA.DAS.AssessorService.Database/Script.PostDeployment1.sql
  src/SFA.DAS.AssessorService.Web/Views/Account/AccessDeniedForPrivilege.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Account/CreateAnAccount.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Account/RequestSent.cshtml
  src/SFA.DAS.AssessorService.Web/Views/ManageUsers/InviteUser/Invited.cshtml
Labels: Requires testing

#828 Remove the word "new" from link
  src/SFA.DAS.AssessorService.Web/Views/Dashboard/Index.cshtml
Labels: Tested

#840 On 2073 feature not available for non-existent privileges
  src/SFA.DAS.AssessorService.Application/Handlers/UserManagement/NotifyUserManagementUsersHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/UserManagement/RequestForPrivilegeHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/UserManagement/SetContactPrivilegesHandler.cs
  src/SFA.DAS.AssessorService.Database/Script.PostDeployment1.sql
  src/SFA.DAS.AssessorService.Database/Tables/Privileges.sql
  src/SFA.DAS.AssessorService.Domain/Consts/Privileges.cs
  src/SFA.DAS.AssessorService.Domain/Entities/Privilege.cs
  src/SFA.DAS.AssessorService.Web/Controllers/AccountController.cs
  src/SFA.DAS.AssessorService.Web/StartupConfiguration/PrivilegeHandler.cs
  src/SFA.DAS.AssessorService.Web/Views/Account/RequestSent.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Account/UnavailableFeature.cshtml
Labels: Ready for Release, Tested

#843 ON-2118 - Fixed bug where a null email address anywhere in Contacts table would…
  src/SFA.DAS.AssessorService.Data/ContactQueryRepository.cs
Labels: Ready for Release, Tested

#836 ON-2012 Record search data for search requests for all search requests; includes IsPrivatelyFunded.
  src/SFA.DAS.AssessorService.Api.Types/Models/SearchData.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Search/When_search_completed_for_non_private_fundeded.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Search/When_search_completed_for_private_fundeded.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Search/SearchHandler.cs
  src/SFA.DAS.AssessorService.Data/AssessorDbContext.cs
  src/SFA.DAS.AssessorService.Data/DapperTypeHandlers/SearchDataHandler.cs
  src/SFA.DAS.AssessorService.Data/DapperTypeHandlers/StandardDataHandler.cs
  src/SFA.DAS.AssessorService.Domain/Entities/SearchData.cs
  src/SFA.DAS.AssessorService.Domain/Entities/SearchLog.cs
Labels: Ready for Release, Tested

#820 On 1999 v1 print function not updating certificates
  src/SFA.DAS.AssessorService.Api.Types/Models/Certificates/UpdateCertificatesBatchNumberRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/Certificates/UpdateCertificatesBatchToIndicatePrintedRequest.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/CertificateController.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Certificates/UpdateCertificatesBatchNumberHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Certificates/UpdateCertificatesBatchToIndicatePrintedHandler.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/ICertificateRepository.cs
  src/SFA.DAS.AssessorService.Application/Mapping/CustomResolvers/BatchNumberResolver.cs
  src/SFA.DAS.AssessorService.Data/CertificateRepository.cs
  src/SFA.DAS.AssessorService.Domain/Consts/CertificateActions.cs
  src/SFA.DAS.AssessorService.EpaoImporter/Const/FunctionName.cs
  src/SFA.DAS.AssessorService.EpaoImporter/Data/AssessorServiceApi.cs
  src/SFA.DAS.AssessorService.EpaoImporter/Data/IAssessorServiceApi.cs
  src/SFA.DAS.AssessorService.EpaoImporter/DomainServices/CertificateReponseExtensions.cs
  src/SFA.DAS.AssessorService.EpaoImporter/Notification/IPrivatelyFundedCertificatesApprovalNotification.cs
  src/SFA.DAS.AssessorService.EpaoImporter/Notification/PrivatelyFundedCertificatesApprovalNotification.cs
  src/SFA.DAS.AssessorService.EpaoImporter/PrintProcessCommand.cs
  src/SFA.DAS.AssessorService.EpaoImporter/PrivatelyFundedCertificatesApprovalCommand.cs
  src/SFA.DAS.AssessorService.EpaoImporter/PrivatelyFundedCertificatesApprovalNotificationService.cs
  src/SFA.DAS.AssessorService.EpaoImporter/SFA.DAS.AssessorService.EpaoImporter.csproj
  src/SFA.DAS.AssessorService.EpaoImporter/Startup/DependencyResolution/HttpRegistry.cs
  src/SFA.DAS.AssessorService.EpaoImporter/Startup/PrivatelyFundedCertificateApprovalsBootstrapper.cs
  src/SFA.DAS.AssessorService.EpaoImporter/nlog.approvals.config
  src/SFA.DAS.AssessorService.PrintFunction.Tests/AssessorServiceApi/WhenSystemChangesStatusesToPrinted.cs
  src/SFA.DAS.AssessorService.PrintFunction.Tests/AssessorServiceApi/WhenSystemRequestsCertificatesToBePrinted.cs
  src/SFA.DAS.AssessorService.PrintFunction.Tests/SFA.DAS.AssessorService.PrintFunction.Tests.csproj
  src/SFA.DAS.AssessorService.PrintFunction.Tests/WhenPrinterFunctionFlowCommandIsExecutedSuccessfully.cs
Labels: Ready for Release, Tested

#830 ON-1663 Using AAD auth for Apply Internal API
  src/SFA.DAS.AssessorService.Api.Types/Models/MigrateContactOrganisation.cs
  src/SFA.DAS.AssessorService.Api.Types/SFA.DAS.AssessorService.Api.Types.csproj
  src/SFA.DAS.AssessorService.Application.Api.Client/ApplyTokenService.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/ContactApplyClient.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/ContactsApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/IContactsApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/OrganisationsApplyApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/ITokenService.cs
  src/SFA.DAS.AssessorService.Application.Api.UnitTests/Controllers/Contacts/Query/ContactsQueryBase.cs
  src/SFA.DAS.AssessorService.Application.Api.UnitTests/Controllers/Contacts/Query/When_GetPrivilegesForContact_called.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/ContactQueryController.cs
  src/SFA.DAS.AssessorService.Web/Startup.cs
Labels: Ready for Release, Tested

#842 ON-2108 Any User From Organisation Can See All Assessments
  src/SFA.DAS.AssessorService.Api.Types/Models/Certificates/GetCertificateHistoryRequest.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/CertificateApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/CertificateQueryController.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Certificates/Query/WhenGetCertificateHistoryHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Certificates/GetCertificatesHistoryHandler.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/ICertificateRepository.cs
  src/SFA.DAS.AssessorService.Data/CertificateRepository.cs
  src/SFA.DAS.AssessorService.Web/Controllers/CertificateHistoryController.cs
Labels: Ready for Release, Tested

#794 ON-1944 Added the email of person who recorded to certification to the summary details.
  src/SFA.DAS.AssessorService.Api.Types/Models/Certificates/CertificateSummaryResponse.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Certificates/GetCertificatesToBeApprovedHandler.cs
Labels: Ready for Release, Tested

#795 ON-1934 - A certificate when displayed in the staff application will show the funding type if it is privately funded.
  src/SFA.DAS.AssessorService.Api.Types/Models/LearnerDetail.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Staff/LearnerDetailHandler.cs
Labels: Requires testing, Staff App

#813 ON-1972 Organisations Without Contacts Being Created In Apply
  src/SFA.DAS.AssessorService.Web/Controllers/OrganisationSearchController.cs
Labels: Tested

#816 ON-1976 simplify (and correct) the getting of Primary or First contact
  src/SFA.DAS.AssessorService.Database/StoredProcedures/EPAO_Register_list_of_organisations.sql
Labels: Tested
