Repository SkillsFundingAgency/das-assessor-service, pull requests merged in 2019-06, with the labels that each got.

#760 ON-1852 Move survey back into phase banner and change survey destination
  src/SFA.DAS.AssessorService.Web/Views/CertificateHistory/Index.cshtml
  src/SFA.DAS.AssessorService.Web/Views/OrganisationStandards/Index.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Search/_SearchForm.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Shared/_DashboardLayout.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Shared/_Layout.cshtml
Labels: Tested

#766 APR-469 bug fixed
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/Roatp/AddRoatpOrganisationController.cs
Labels: RoATP, Tested

#773 ON-1933 - Amend options for ST0331 & ST0332
  src/SFA.DAS.AssessorService.Database/Script.PostDeployment1.sql
Labels: Tested

#770 ON-1789 The ukprn is required for a live organisation
  src/SFA.DAS.AssessorService.Application.Api/Consts/EpaOrganisationValidatorMessageName.cs
  src/SFA.DAS.AssessorService.Application.Api/Resources/Validators/EpaOrganisationValidator.en.resx
  src/SFA.DAS.AssessorService.Application.Api/Validators/EpaOrganisationValidator.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/IEpaOrganisationValidator.cs
  src/SFA.DAS.AssessorService.Web.Staff/Views/Register/EditOrganisation.cshtml
Labels: Tested

#772 ON-1173 secondary app submissions v2
  src/SFA.DAS.AssessorService.Api.Types/Commands/CreateOrganisationContactCommand.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Login/LoginHandlerTestsBase.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Login/When_EPAO_is_NotActivated.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Login/LoginHandler.cs
  src/SFA.DAS.AssessorService.Web.Staff.Tests/Services/AnswerServiceGatherAnswersTests.cs
  src/SFA.DAS.AssessorService.Web.Staff/Infrastructure/ApplyApiClient.cs
  src/SFA.DAS.AssessorService.Web.Staff/Infrastructure/IApplyApiClient.cs
  src/SFA.DAS.AssessorService.Web.Staff/Services/AnswerInjectionService.cs
  src/SFA.DAS.AssessorService.Web.Staff/Services/AnswerService.cs
  src/SFA.DAS.AssessorService.Web/StartupConfiguration/AuthenticationStartup.cs
Labels: OnBothServices, Staff App, Tested

#769 On 1924 use application json post submit data
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/CertificateApprovalsController.cs
  src/SFA.DAS.AssessorService.Web.Staff/ViewModels/Private/CertificateApprovalPostViewModel.cs
  src/SFA.DAS.AssessorService.Web.Staff/Views/CertificateApprovals/_ApprovalsScriptsPartial.cshtml
Labels: Tested

#747 ON-1525 Updated SQL for search for ILRs using uln as per alan recommendation
  src/SFA.DAS.AssessorService.Data/IlrRepository.cs
Labels: Tested

#644 ON-1829 Fixed financial download link to deal with multiple uploads
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/Apply/FinancialController.cs
Labels: OnBothServices, Public-Beta, Staff App, Tested

#746 On 1851 edit user permissions
  src/SFA.DAS.AssessorService.Api.Types/Models/GetEmailTemplateRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/UserManagement/SetContactPrivilegesRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/UserManagement/SetContactPrivilegesResponse.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/ContactsApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/ContactController.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/ContactQueryController.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/EMailTemplateQueryController.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/OrganisationController.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Contacts/SetContactPrivilegesHandlerTests/When_handling_set_contact_privileges_request.cs
  src/SFA.DAS.AssessorService.Application/Handlers/EMailTemplates/GetEmailTemplateHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/UserManagement/SetContactPrivilegesHandler.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/IContactRepository.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/IEMailTemplateQueryRepository.cs
  src/SFA.DAS.AssessorService.Data.UnitTests/Contacts/WhenCreatePersistsData.cs
  src/SFA.DAS.AssessorService.Data.UnitTests/Contacts/WhenDeleteContactPersistsData.cs
  src/SFA.DAS.AssessorService.Data.UnitTests/Contacts/WhenDeletePersistsDataAndIsNotFound.cs
  src/SFA.DAS.AssessorService.Data/AssessorDbContext.cs
  src/SFA.DAS.AssessorService.Data/ContactRepository.cs
  src/SFA.DAS.AssessorService.Data/EMailTemplateQueryRepository.cs
  src/SFA.DAS.AssessorService.Database/SFA.DAS.AssessorService.Database.sqlproj
  src/SFA.DAS.AssessorService.Database/Script.PostDeployment1.sql
  src/SFA.DAS.AssessorService.Database/Tables/ContactLogs.sql
  src/SFA.DAS.AssessorService.Database/Tables/ContactsPrivileges.sql
  src/SFA.DAS.AssessorService.Database/Tables/Privileges.sql
  src/SFA.DAS.AssessorService.Domain/Entities/ContactLog.cs
  src/SFA.DAS.AssessorService.Domain/Entities/ContactsPrivilege.cs
  src/SFA.DAS.AssessorService.Domain/Entities/Privilege.cs
  src/SFA.DAS.AssessorService.Domain/SFA.DAS.AssessorService.Domain.csproj
  src/SFA.DAS.AssessorService.Web.UnitTests/ManageUsersTests/UserDetailsControllerTests/UserDetailsControllerTestsBase.cs
  src/SFA.DAS.AssessorService.Web.UnitTests/ManageUsersTests/UserDetailsControllerTests/When_User_is_called_by_valid_user.cs
  src/SFA.DAS.AssessorService.Web.UnitTests/ManageUsersTests/UserDetailsControllerTests/When_permissions_are_updated.cs
  src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/ManageUsersBaseController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/UserDetailsController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/ViewModels/PermissionsViewModel.cs
  src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/ViewModels/UserViewModel.cs
  src/SFA.DAS.AssessorService.Web/StartupConfiguration/AuthenticationStartup.cs
  src/SFA.DAS.AssessorService.Web/Views/ManageUsers/UserDetails/EditUserPermissions.cshtml
  src/SFA.DAS.AssessorService.Web/Views/ManageUsers/UserDetails/User.cshtml
  src/SFA.DAS.AssessorService.Web/Views/ManageUsers/UserDetails/_UserDetails.cshtml
Labels: Manage Users, Requires testing

#750 On 1862 remove user
  src/SFA.DAS.AssessorService.Api.Types/Models/UserManagement/RemoveContactFromOrganisationRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/UserManagement/RemoveContactFromOrganisationResponse.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/ContactApplyClient.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/ContactsApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/IContactsApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/ContactController.cs
  src/SFA.DAS.AssessorService.Application.Api/StartupConfiguration/Startup.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Contacts/WhenRetrieveContactsWithPrivileges.cs
  src/SFA.DAS.AssessorService.Application/Handlers/ContactHandlers/RetrieveContactsWithPrivilagesHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/UserManagement/PrivilegesHandlerBase.cs
  src/SFA.DAS.AssessorService.Application/Handlers/UserManagement/RemoveContactFromOrganisationHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/UserManagement/SetContactPrivilegesHandler.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/IContactQueryRepository.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/IContactRepository.cs
  src/SFA.DAS.AssessorService.Data/ContactQueryRepository.cs
  src/SFA.DAS.AssessorService.Data/ContactRepository.cs
  src/SFA.DAS.AssessorService.Database/Script.PostDeployment1.sql
  src/SFA.DAS.AssessorService.Domain/Entities/ContactLog.cs
  src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/ManageUsersBaseController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/UserDetailsController.cs
  src/SFA.DAS.AssessorService.Web/Views/ManageUsers/Index.cshtml
  src/SFA.DAS.AssessorService.Web/Views/ManageUsers/UserDetails/RemoveConfirm.cshtml
Labels: Manage Users

#777 On 1862 Add extra User Removed screen
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/OrganisationsApiClient.cs
  src/SFA.DAS.AssessorService.Web.UnitTests/ManageUsersTests/UserDetailsControllerTests/UserDetailsControllerTestsBase.cs
  src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/UserDetailsController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/ViewModels/UserRemovedViewModel.cs
  src/SFA.DAS.AssessorService.Web/Views/ManageUsers/UserDetails/Removed.cshtml
Labels: Manage Users

#748 Apr 471 ukrlp service is unavailable
  src/SFA.DAS.AssessorService.Web.Staff.Tests/Controllers/Roatp/AddRoatpOrganisationControllerTests.cs
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/Roatp/AddRoatpOrganisationController.cs
  src/SFA.DAS.AssessorService.Web.Staff/Validators/Roatp/AddOrganisatioViaUkprnViewModelValidator.cs
  src/SFA.DAS.AssessorService.Web.Staff/Validators/Roatp/UkrlpNotFoundViewModelValidator.cs
  src/SFA.DAS.AssessorService.Web.Staff/ViewModels/Roatp/UkrlpNotFoundViewModel.cs
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/AddOrganisation.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/UkprnIsUnavailable.cshtml
Labels: Do not merge, RoATP, Tested

#749 On 1888 changing std on check and amend
  src/SFA.DAS.AssessorService.Web.Staff.Tests/Controllers/Given_I_request_the_options_page.cs
  src/SFA.DAS.AssessorService.Web.Staff.Tests/Controllers/PrivateCertificateTests/Posts/Given_I_post_the_standard_code_page.cs
  src/SFA.DAS.AssessorService.Web.Staff.Tests/Controllers/WhenUserLoadsAmendOptionPage.cs
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/CertificateOptionController.cs
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/Private/CertificatePrivateStandardCodeController.cs
  src/SFA.DAS.AssessorService.Web.Staff/ViewModels/CertificateOptionViewModel.cs
  src/SFA.DAS.AssessorService.Web.Staff/Views/CertificateAmend/Option.cshtml
  src/SFA.DAS.AssessorService.Web/Controllers/CertificateBaseController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/CertificateOptionController.cs
  src/SFA.DAS.AssessorService.Web/ViewModels/Certificate/CertificateOptionViewModel.cs
  src/SFA.DAS.AssessorService.Web/Views/Certificate/Grade.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Certificate/LastName.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Certificate/LearnerStartDate.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Certificate/Option.cshtml
  src/SFA.DAS.AssessorService.Web/wwwroot/css/site.min.css
  src/SFA.DAS.AssessorService.Web/wwwroot/js/epao-validation.min.js
  src/SFA.DAS.AssessorService.Web/wwwroot/js/postcode-lookup-service.min.js
  src/SFA.DAS.AssessorService.Web/wwwroot/js/site.min.js
Labels: Tested

#784 On 1857 application of permissions
  src/SFA.DAS.AssessorService.Api.Types/Models/UserManagement/RequestForPrivilegeRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/UserManagement/SetContactPrivilegesResponse.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/ContactsApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/IContactsApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/ContactController.cs
  src/SFA.DAS.AssessorService.Application/Handlers/UserManagement/RequestForPrivilegeHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/UserManagement/SetContactPrivilegesHandler.cs
  src/SFA.DAS.AssessorService.Database/Script.PostDeployment1.sql
  src/SFA.DAS.AssessorService.Database/Tables/Privileges.sql
  src/SFA.DAS.AssessorService.Domain/Consts/Privileges.cs
  src/SFA.DAS.AssessorService.Domain/Entities/Privilege.cs
  src/SFA.DAS.AssessorService.Web.UnitTests/ControllerTests/ControllerAuthorizeAttributeTests.cs
  src/SFA.DAS.AssessorService.Web/Controllers/AccountController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/ApplyToAssessStandardController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/CertificateHistoryController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/ExternalApiController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/InviteUserController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/ManageUsersBaseController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/ManageUsersController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/RequestAccessController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/UserDetailsController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/OrganisationStandardsController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/SearchController.cs
  src/SFA.DAS.AssessorService.Web/Startup.cs
  src/SFA.DAS.AssessorService.Web/StartupConfiguration/AuthenticationStartup.cs
  src/SFA.DAS.AssessorService.Web/StartupConfiguration/DeniedPrivilegeContext.cs
  src/SFA.DAS.AssessorService.Web/StartupConfiguration/PrivilegeAuthorizeAttribute.cs
  src/SFA.DAS.AssessorService.Web/StartupConfiguration/PrivilegeHandler.cs
  src/SFA.DAS.AssessorService.Web/StartupConfiguration/PrivilegePolicyProvider.cs
  src/SFA.DAS.AssessorService.Web/StartupConfiguration/PrivilegeRequirement.cs
  src/SFA.DAS.AssessorService.Web/ViewModels/Account/AccessDeniedViewModel.cs
  src/SFA.DAS.AssessorService.Web/Views/Account/AccessDeniedForPrivilege.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Account/RequestSent.cshtml
  src/SFA.DAS.AssessorService.Web/Views/ApplyToAssessStandard/Index.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Dashboard/Index.cshtml
  src/SFA.DAS.AssessorService.Web/Views/ManageUsers/InviteUser/Invite.cshtml
  src/SFA.DAS.AssessorService.Web/Views/ManageUsers/InviteUser/Invited.cshtml
  src/SFA.DAS.AssessorService.Web/Views/ManageUsers/UserDetails/EditUserPermissions.cshtml
  src/SFA.DAS.AssessorService.Web/Views/ManageUsers/UserDetails/RemoveConfirm.cshtml
  src/SFA.DAS.AssessorService.Web/Views/ManageUsers/UserDetails/Removed.cshtml
  src/SFA.DAS.AssessorService.Web/Views/ManageUsers/UserDetails/User.cshtml
Labels: Manage Users

#759 ON-1637 New search results page layout
  src/SFA.DAS.AssessorService.Api.Types/Models/AO/AssessmentOrganisationSummary.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/OrganisationSearchResult.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/OrganisationsApplyApiClient.cs
  src/SFA.DAS.AssessorService.Data/RegisterQueryRepository.cs
  src/SFA.DAS.AssessorService.Web/Controllers/OrganisationSearchController.cs
  src/SFA.DAS.AssessorService.Web/StartupConfiguration/MappingStartup.cs
  src/SFA.DAS.AssessorService.Web/ViewModels/Organisation/OrganisationSearchViewModel.cs
  src/SFA.DAS.AssessorService.Web/ViewModels/Organisation/RequestAccessOrgSearchViewModel.cs
  src/SFA.DAS.AssessorService.Web/Views/OrganisationSearch/Confirm.cshtml
  src/SFA.DAS.AssessorService.Web/Views/OrganisationSearch/DealingWithRequest.cshtml
  src/SFA.DAS.AssessorService.Web/Views/OrganisationSearch/NoAccess.cshtml
  src/SFA.DAS.AssessorService.Web/Views/OrganisationSearch/Results.cshtml
  src/SFA.DAS.AssessorService.Web/Views/OrganisationSearch/Type.cshtml
  src/SFA.DAS.AssessorService.Web/Views/OrganisationSearch/_OrgSearchPaginationLinks.cshtml
  src/SFA.DAS.AssessorService.Web/wwwroot/javascripts/postcode-lookup-service.js
  src/SFA.DAS.AssessorService.Web/wwwroot/stylesheets/application.css
Labels: OnBothServices, Tested

#785 ON-1940 Organisations exempt from financial's journey not working as it should
  src/SFA.DAS.AssessorService.Application.Api/Controllers/ContactQueryController.cs
  src/SFA.DAS.AssessorService.Database/Tables/Privileges.sql
Labels: Tested

#786 ON-1939 Error when adding a new contact in staff app
  src/SFA.DAS.AssessorService.Application.Api/Consts/EpaOrganisationValidatorMessageName.cs
  src/SFA.DAS.AssessorService.Application.Api/Validators/EpaOrganisationValidator.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/IEpaOrganisationValidator.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/IRegisterValidationRepository.cs
  src/SFA.DAS.AssessorService.Data/RegisterValidationRepository.cs
Labels: Tested

#767 ON-1847 Fixes for IFA standards API
  src/SFA.DAS.AssessorService.Application.Api/Services/StandardService.cs
  src/SFA.DAS.AssessorService.Data/StandardRepository.cs
  src/SFA.DAS.AssessorService.EpaoImporter/PrintFunctionFlow.cs
  src/SFA.DAS.AssessorService.EpaoImporter/PrivatelyFundedCertificatesApprovalNotificationService.cs
  src/SFA.DAS.AssessorService.EpaoImporter/StandardCollationFlow.cs
  src/SFA.DAS.AssessorService.ExternalApis/IFAStandards/IfaStandardsApiClient.cs
  src/SFA.DAS.AssessorService.ExternalApis/IFAStandards/Types/IfaStandard.cs
  src/SFA.DAS.AssessorService.Web/Startup.cs
Labels: Requires testing

#791 ON-1961 CSS updated to the latest version for Company Not Active Screen
  src/SFA.DAS.AssessorService.Web/Views/OrganisationSearch/CompanyNotActive.cshtml
Labels: Tested

#790 ON-1960 Error When Adding A New Contact To An Organisation
  src/SFA.DAS.AssessorService.Application.Api/Validators/EpaOrganisationValidator.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/IEpaOrganisationValidator.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/IRegisterValidationRepository.cs
  src/SFA.DAS.AssessorService.Data/RegisterValidationRepository.cs
  src/SFA.DAS.AssessorService.Web/Resources/Validators/CertificateCheckViewModelValidator.Designer.cs
Labels: Tested

#792 On 1938 self registration approval
  src/SFA.DAS.AssessorService.Api.Types/Models/EmailAllApprovedContactsRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/NotifyUserManagementUsersRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/UserManagement/ApproveContactRequest.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/ContactsApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/IContactsApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/IOrganisationsApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/OrganisationsApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/ContactController.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/OrganisationController.cs
  src/SFA.DAS.AssessorService.Application/Handlers/ContactHandlers/CreateContactHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/ContactHandlers/UpdateSignInId/UpdateSignInIdHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/OrganisationHandlers/GetContactsForOrganisationHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/UserManagement/ApproveContactHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/UserManagement/NotifyUserManagementUsersHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/UserManagement/RejectContactHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/UserManagement/RemoveContactFromOrganisationHandler.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/IContactRepository.cs
  src/SFA.DAS.AssessorService.Data/ContactQueryRepository.cs
  src/SFA.DAS.AssessorService.Data/ContactRepository.cs
  src/SFA.DAS.AssessorService.Database/Script.PostDeployment1.sql
  src/SFA.DAS.AssessorService.Domain/Consts/ContactStatus.cs
  src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/ManageUsersController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/UserDetailsController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/ViewModels/PermissionsViewModel.cs
  src/SFA.DAS.AssessorService.Web/Controllers/OrganisationSearchController.cs
  src/SFA.DAS.AssessorService.Web/Views/ManageUsers/UserDetails/EditUserPermissions.cshtml
  src/SFA.DAS.AssessorService.Web/Views/ManageUsers/UserDetails/User.cshtml
  src/SFA.DAS.AssessorService.Web/Views/ManageUsers/UserDetails/_UserDetails.cshtml
Labels: Manage Users

#782 ON-1650 - Show Privately Funded in Certificate Number search
  src/SFA.DAS.AssessorService.Data/Staff/StaffIlrRepository.cs
Labels: Ready for Release, Staff App, Tested

#761 Apr 473 add provider using details from ukrlp
  src/SFA.DAS.AssessorService.Api.Types/Models/Roatp/CreateOrganisationRequest.cs
  src/SFA.DAS.AssessorService.Web.Staff.Tests/Controllers/Roatp/AddRoatpOrganisationControllerTests.cs
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/Roatp/AddRoatpOrganisationController.cs
  src/SFA.DAS.AssessorService.Web.Staff/Validators/Roatp/AddOrganisationTypeViewModelValidator.cs
  src/SFA.DAS.AssessorService.Web.Staff/Validators/Roatp/RoatpOrganisationValidator.cs
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/AddOrganisationPreview.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/AddOrganisationType.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/AddProviderType.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/UkprnPreview.cshtml
Labels: Do not merge, RoATP, Tested

#787 Apr 494 application determined date in add provider journey
  src/SFA.DAS.AssessorService.Api.Types/Models/Roatp/CreateOrganisationRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/Roatp/OrganisationData.cs
  src/SFA.DAS.AssessorService.Domain/Entities/OrganisationData.cs
  src/SFA.DAS.AssessorService.Web.Staff.Tests/Controllers/Roatp/AddRoatpOrganisationControllerTests.cs
  src/SFA.DAS.AssessorService.Web.Staff.Tests/Validators/AddApplicationDeterminedDateViewModelValidatorTests.cs
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/Roatp/AddRoatpOrganisationController.cs
  src/SFA.DAS.AssessorService.Web.Staff/Resources/RoatpOrganisationValidation.Designer.cs
  src/SFA.DAS.AssessorService.Web.Staff/Resources/RoatpOrganisationValidation.resx
  src/SFA.DAS.AssessorService.Web.Staff/Validators/Roatp/AddApplicationDeterminedDateViewModelValidator.cs
  src/SFA.DAS.AssessorService.Web.Staff/Validators/Roatp/RoatpOrganisationValidator.cs
  src/SFA.DAS.AssessorService.Web.Staff/ViewModels/Roatp/AddOrganisationViewModel.cs
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/AddApplicationDeterminedDate.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/AddOrganisationPreview.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/AddOrganisationType.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/SearchResults.cshtml
Labels: Do not merge, RoATP, Tested

#793 APR-484 page simplified
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/Roatp/AddRoatpOrganisationController.cs
  src/SFA.DAS.AssessorService.Web.Staff/Validators/Roatp/UkrlpNotFoundViewModelValidator.cs
  src/SFA.DAS.AssessorService.Web.Staff/ViewModels/Roatp/UkrlpNotFoundViewModel.cs
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/UkprnIsUnavailable.cshtml
Labels: Do not merge, RoATP

#805 Apr 528 enhance companies house number validation
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/Roatp/AddRoatpOrganisationController.cs
  src/SFA.DAS.AssessorService.Web.Staff/Validators/Roatp/RoatpOrganisationValidator.cs
Labels: Do not merge, RoATP

#802 ON-1981 - Hotfix to Record All Assessments
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Certificates/UpdateCertificateHandlerTests/When_called_and_existing_certificate.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Certificates/Batch/CreateBatchCertificateHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Certificates/Batch/UpdateBatchCertificateHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Certificates/UpdateCertificateHandler.cs
  src/SFA.DAS.AssessorService.Database/Script.PostDeployment1.sql
Labels: Tested

#804 ON-1908 Standard not displaying for a registered organisation
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/OrganisationsApiClient.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Search/SearchHandlerTestBase.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Search/When_assessmentorgs_api_returns_non_int_stdcode.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Search/When_returned_learners_do_not_match_users_epaorgid.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Search/When_returned_learners_match_users_epaorgid.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Search/SearchHandler.cs
  src/SFA.DAS.AssessorService.Web.UnitTests/MockedObjects/MockedAssessmentOrgsApiClient.cs
  src/SFA.DAS.AssessorService.Web.UnitTests/MockedObjects/MockedOrganisationsApiClient.cs
  src/SFA.DAS.AssessorService.Web.UnitTests/PrivateCertificateTests/Posts/CertificatePostBase.cs
  src/SFA.DAS.AssessorService.Web.UnitTests/PrivateCertificateTests/Posts/Given_I_post_the_standard_code_page.cs
  src/SFA.DAS.AssessorService.Web.UnitTests/PrivateCertificateTests/Posts/Given_I_post_the_standard_code_page_with_invalid_model.cs
  src/SFA.DAS.AssessorService.Web.UnitTests/PrivateCertificateTests/Queries/CertificateQueryBase.cs
  src/SFA.DAS.AssessorService.Web.UnitTests/PrivateCertificateTests/Queries/Given_I_request_the_standard_code_page.cs
  src/SFA.DAS.AssessorService.Web.UnitTests/PrivateCertificateTests/Queries/Given_I_request_the_standard_code_page_and_session_does_not_exist.cs
  src/SFA.DAS.AssessorService.Web.UnitTests/PrivateCertificateTests/Queries/Given_I_request_the_standard_code_page_on_redirect_to_check_page.cs
  src/SFA.DAS.AssessorService.Web.UnitTests/PrivateCertificateTests/Validators/CertificateValidatorBase.cs
  src/SFA.DAS.AssessorService.Web/Controllers/Private/CertificatePrivateStandardCodeController.cs
Labels: Tested

#808 ON-1929 PostCode Lookup Not Working Or Showing From_Fail To Pass
  src/SFA.DAS.AssessorService.Web/Controllers/CertificateAddressSummaryController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/CertificateBaseController.cs
  src/SFA.DAS.AssessorService.Web/Views/Certificate/AddressSummary.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Certificate/Check.cshtml
Labels: Tested

#799 ON-1958 - Added several fixes to stop user seeing data they shouldn't
  src/SFA.DAS.AssessorService.Web/Controllers/AccountController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/HomeController.cs
Labels: Tested
