Repository SkillsFundingAgency/das-assessor-service, pull requests merged in 2019-08, with the labels that each got.

#851 ON-2134 admin services security fixes
  src/SFA.DAS.AssessorService.Api.Types/Models/GetEpaContactByEmailRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/GetEpaContactBySignInIdRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/Register/AssociateEpaOrganisationWithEpaContactRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/Register/CreateEpaOrganisationRequest.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/RegisterController.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/RegisterQueryController.cs
  src/SFA.DAS.AssessorService.Application/Handlers/EpaOrganisationHandlers/AssociateEpaOrganisationWithEpaContactHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/EpaOrganisationHandlers/CreateEpaOrganisationHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/ao/GetEpaContactByEmailHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/ao/GetEpaContactBySignInIdHandler.cs
Labels: Ready for Release, Tested

#854 ON-1833 - Organisation Status changing from LIVE to NEW fix
  src/SFA.DAS.AssessorService.Application/Handlers/OrganisationHandlers/UpdateOrganisationHandler.cs
  src/SFA.DAS.AssessorService.Data/OrganisationRepository.cs
Labels: Requires testing

#856 ON-1005 Removed Fails from certificate reports
  src/SFA.DAS.AssessorService.Data/Staff/StaffReportRepository.cs
  src/SFA.DAS.AssessorService.Database/StoredProcedures/StaffReports_DetailedExtract.sql
  src/SFA.DAS.AssessorService.Database/StoredProcedures/StaffReports_MonthlySummary.sql
  src/SFA.DAS.AssessorService.Database/StoredProcedures/StaffReports_WeeklySummary.sql
Labels: Ready for Release, Tested

#866 ON-2067 Added Back to user list link at bottom of page and changed back link …
  src/SFA.DAS.AssessorService.Web/Views/ManageUsers/UserDetails/EditUserPermissions.cshtml
Labels: Ready for Release, Tested

#869 ON-2185 Add EpaorgId to header
  src/SFA.DAS.AssessorService.Web/Controllers/AccountController.cs
  src/SFA.DAS.AssessorService.Web/Views/Shared/_DashboardLayout.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Shared/_Layout.cshtml
  src/SFA.DAS.AssessorService.Web/wwwroot/stylesheets/application.css
Labels: Ready for Release, Tested

#865 ON-2123 - Pipeline updates
  src/SFA.DAS.AssessorService.Application/Handlers/Standards/GetEpaoPipelineStandardsExtractHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Standards/GetEpaoPipelineStandardsHandler.cs
  src/SFA.DAS.AssessorService.Web/Views/OrganisationStandards/Pipelines.cshtml
  src/SFA.DAS.AssessorService.Web/wwwroot/stylesheets/application.css
Labels: TestInProgress

#872 On 2223 data summaries for opportunity finder
  src/SFA.DAS.AssessorService.Database/SFA.DAS.AssessorService.Database.sqlproj
  src/SFA.DAS.AssessorService.Database/StoredProcedures/Data_Summaries.sql
  src/SFA.DAS.AssessorService.Database/Tables/StandardSummary.sql
Labels: Requires testing

#875 On 2193 new user account created email invitor
  src/SFA.DAS.AssessorService.Application.Api/Controllers/ContactController.cs
  src/SFA.DAS.AssessorService.Application/Handlers/UserManagement/InvitationCheckHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/UserManagement/InvitationCheckRequest.cs
  src/SFA.DAS.AssessorService.Application/Handlers/UserManagement/InviteContactToOrganisationHandler.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/IContactRepository.cs
  src/SFA.DAS.AssessorService.Data/AssessorDbContext.cs
  src/SFA.DAS.AssessorService.Data/ContactRepository.cs
  src/SFA.DAS.AssessorService.Database/SFA.DAS.AssessorService.Database.sqlproj
  src/SFA.DAS.AssessorService.Database/Script.PostDeployment1.sql
  src/SFA.DAS.AssessorService.Database/Tables/ContactInvitations.sql
  src/SFA.DAS.AssessorService.Domain/Entities/ContactInvitation.cs
Labels: Ready for Release, Tested

#882 ON-2242_Improve_Monthly_Detailed_Extract
  src/SFA.DAS.AssessorService.Database/StoredProcedures/StaffReports_DetailedExtract.sql
  src/SFA.DAS.AssessorService.Database/Tables/Certificates.sql
Labels: Ready for Release, Tested

#878 ON-2241_Configure_HTTP_Header_from_Security_Audit
  src/SFA.DAS.AssessorService.Application.Api.External/Infrastructure/SecurityHeadersExtensions.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Startup.cs
  src/SFA.DAS.AssessorService.Application.Api.External/web.config
Labels: Requires testing

#885 ON-2242_make_Monthly_detailed_extract_a_download
  src/SFA.DAS.AssessorService.Data/Staff/StaffReportRepository.cs
  src/SFA.DAS.AssessorService.Database/Script.PostDeployment1.sql
  src/SFA.DAS.AssessorService.Database/StoredProcedures/StaffReports_DetailedExtract.sql
  src/SFA.DAS.AssessorService.Database/Update-Staff-Reports-Config.sql
Labels: Ready for Release, Tested
