Repository SkillsFundingAgency/das-assessor-service, pull requests merged in 2019-05, with the labels that each got.

#705 ON-1791 - Fixed incorrect column headers
  src/SFA.DAS.AssessorService.Web.Staff/Views/Apply/Applications/RejectedApplications.cshtml
Labels: Tested

#700 ON-1821 Controller authorize tests
  src/SFA.DAS.AssessorService.Application.Api.UnitTests/Controllers/ControllerAuthorizeAttributeTests.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/Apply/ImportController.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/ContactQueryController.cs
  src/SFA.DAS.AssessorService.Web.Staff.Tests/Controllers/ControllerAuthorizeAttributeTests.cs
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/CommentController.cs
  src/SFA.DAS.AssessorService.Web.UnitTests/ControllerTests/ControllerAuthorizeAttributeTests.cs
  src/SFA.DAS.AssessorService.Web/Controllers/CertificateBaseController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/MigrateUsersController.cs
Labels: Tested

#703 ON-1820 Added FromBody to Org Validation Endpoints
  src/SFA.DAS.AssessorService.Application.Api/Controllers/RegisterValidationController.cs
Labels: Tested

#686 APR-294 code done
  src/SFA.DAS.AssessorService.Api.Types/Models/Roatp/OrganisationType.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/Roatp/UpdateOrganisationTypeRequest.cs
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/Roatp/UpdateRoatpOrganisationController.cs
  src/SFA.DAS.AssessorService.Web.Staff/Infrastructure/IRoatpApiClient.cs
  src/SFA.DAS.AssessorService.Web.Staff/Infrastructure/RoatpApiClient.cs
  src/SFA.DAS.AssessorService.Web.Staff/SFA.DAS.AssessorService.Web.Staff.csproj
  src/SFA.DAS.AssessorService.Web.Staff/ViewModels/Roatp/UpdateOrganisationTypeViewModel.cs
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/SearchResults.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/UpdateOrganisationType.cshtml
Labels: RoATP, Tested

#680 APR-392 service shutter pages
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/ErrorPageController.cs
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/TestErrorController.cs
  src/SFA.DAS.AssessorService.Web.Staff/SFA.DAS.AssessorService.Web.Staff.csproj
  src/SFA.DAS.AssessorService.Web.Staff/Startup.cs
  src/SFA.DAS.AssessorService.Web.Staff/Views/ErrorPage/PageNotFound.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/ErrorPage/ServiceError.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/ErrorPage/ServiceUnavailable.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Shared/_ErrorPageLayout.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/wwwroot/inactive_app_offline_public_beta.htm
Labels: RoATP, Tested

#614 ON-1620 use the same filter -
  src/SFA.DAS.AssessorService.Database/StoredProcedures/EPAO_Register_list_of_organisations.sql
  src/SFA.DAS.AssessorService.Database/StoredProcedures/EPAO_Register_list_of_standards.sql
  src/SFA.DAS.AssessorService.Database/StoredProcedures/EPAO_Register_register_delivery_areas.sql
  src/SFA.DAS.AssessorService.Database/StoredProcedures/EPAO_Register_register_organisation.sql
  src/SFA.DAS.AssessorService.Database/StoredProcedures/EPAO_Register_register_standards.sql
Labels: Tested

#694 ON-1805 - Use StandardCollation for Staff Learner Search
  src/SFA.DAS.AssessorService.Application/Handlers/Staff/LearnerDetailHandler.cs
Labels: Tested

#682 APR-420 styling fixes for long legal and trading names
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/SearchResults.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/UpdateOrganisationFinancialTrackRecord.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/UpdateOrganisationLegalName.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/UpdateOrganisationParentCompanyGuarantee.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/UpdateOrganisationProviderType.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/UpdateOrganisationStatus.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/UpdateOrganisationTradingName.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/UpdateOrganisationUkprn.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/wwwroot/css/roatp.css
Labels: RoATP, Tested

#656 APR-410 back navigation fix for add roatp organisation
  src/SFA.DAS.AssessorService.Application.Api/web.config
  src/SFA.DAS.AssessorService.Web.Staff.Tests/Controllers/Roatp/AddRoatpOrganisationControllerTests.cs
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/Roatp/AddRoatpOrganisationController.cs
  src/SFA.DAS.AssessorService.Web.Staff/Properties/launchSettings.json
Labels: RoATP, Tested

#643 Apr 389 download roatp file for fat
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/Roatp/DownloadRoatpController.cs
  src/SFA.DAS.AssessorService.Web.Staff/Infrastructure/IRoatpApiClient.cs
  src/SFA.DAS.AssessorService.Web.Staff/Infrastructure/RoatpApiClient.cs
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/Index.cshtml
Labels: RoATP, Tested

#715 ON-1818 - Do not preselect Organisation type
  src/SFA.DAS.AssessorService.Web/Controllers/OrganisationSearchController.cs
Labels: Tested

#711 ON-1832 - Fixed incorrect validation endpoint
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/OrganisationsApiClient.cs
Labels: Tested

#714 Added changes to clean up null names as per ON-1822
  src/SFA.DAS.AssessorService.EpaoDataSync/Domain/IlrsRefresherService.cs
Labels: Ready for Release

#716 ON-1834 Added extra security headers
  src/SFA.DAS.AssessorService.Application.Api/StartupConfiguration/SecurityHeadersExtensions.cs
  src/SFA.DAS.AssessorService.Application.Api/StartupConfiguration/Startup.cs
  src/SFA.DAS.AssessorService.Web.Extensions/SFA.DAS.AssessorService.Web.Extensions.csproj
  src/SFA.DAS.AssessorService.Web.Extensions/SecurityHeadersExtensions.cs
  src/SFA.DAS.AssessorService.Web.Staff/Startup.cs
  src/SFA.DAS.AssessorService.Web/Startup.cs
Labels: Tested

#717 Apr 464 fix provider type change
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/Roatp/UpdateRoatpOrganisationController.cs
  src/SFA.DAS.AssessorService.Web.Staff/ViewModels/Roatp/UpdateOrganisationProviderTypeViewModel.cs
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/UpdateOrganisationProviderType.cshtml
Labels: RoATP, Tested

#718 ON-1839 - Check company is actively trading
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/ApiClientBase.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/OrganisationsApplyApiClient.cs
  src/SFA.DAS.AssessorService.Web/Controllers/OrganisationSearchController.cs
  src/SFA.DAS.AssessorService.Web/Views/OrganisationSearch/CompanyNotActive.cshtml
Labels: Tested

#723 ON_1650 - Staff ILR search fixes
  src/SFA.DAS.AssessorService.Application/Handlers/Staff/StaffSearchHandler.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/IStaffIlrRepository.cs
  src/SFA.DAS.AssessorService.Data/Staff/StaffIlrRepository.cs
  src/SFA.DAS.AssessorService.Database/SFA.DAS.AssessorService.Database.sqlproj
  src/SFA.DAS.AssessorService.Database/StoredProcedures/StaffSearchCertificates_Count.sql
Labels: Requires testing

#721 Added cache control headers
  src/SFA.DAS.AssessorService.Application.Api/StartupConfiguration/SecurityHeadersExtensions.cs
  src/SFA.DAS.AssessorService.Web.Extensions/CacheOverrideHtmlGenerator.cs
  src/SFA.DAS.AssessorService.Web.Extensions/SecurityHeadersExtensions.cs
  src/SFA.DAS.AssessorService.Web/Startup.cs
  src/SFA.DAS.AssessorService.Web/Views/Shared/_DashboardLayout.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Shared/_Layout.cshtml
Labels: TestInProgress

#719 ON-1689 Using defined framework constants consistently for establishing a login session.
  src/SFA.DAS.AssessorService.Web/Controllers/AccountController.cs
  src/SFA.DAS.AssessorService.Web/Startup.cs
  src/SFA.DAS.AssessorService.Web/StartupConfiguration/AuthenticationStartup.cs
Labels: Tested

#726 ON-1812 Updated functionality to use the given name and family name as highli…
  src/SFA.DAS.AssessorService.Api.Types/Commands/CreateOrganisationContactCommand.cs
  src/SFA.DAS.AssessorService.Web.Staff/Services/AnswerInjectionService.cs
  src/SFA.DAS.AssessorService.Web.Staff/Services/AnswerService.cs
Labels: Tested

#735 ON 1876 Copy changes
  src/SFA.DAS.AssessorService.Web/Views/Home/Index.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Search/_SearchForm.cshtml
Labels: Tested

#730 On 1865 replace fat calls with local db
  src/SFA.DAS.AssessorService.Api.Types/Models/AO/OrganisationStandardSummary.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/SearchStandardsRequest.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/StandardServiceClient.cs
  src/SFA.DAS.AssessorService.Application.Api.UnitTests/Controllers/Register/Query/SearchStandardsBySearchTermTests.cs
  src/SFA.DAS.AssessorService.Application.Api.UnitTests/Controllers/RegisterImport/WhenPostToImport.cs
  src/SFA.DAS.AssessorService.Application.Api.UnitTests/Validators/Certificates/BatchCertificateRequestValidatorTestBase.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/RegisterImportController.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/RegisterQueryController.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/StandardServiceController.cs
  src/SFA.DAS.AssessorService.Application.Api/Services/StandardService.cs
  src/SFA.DAS.AssessorService.Application.Api/Validators/EpaOrganisationValidator.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Certificates/StartCertificateHandlerTests/When_called_and_no_existing_certificate.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Register/Query/RegisterQueryGetStandardsByOrganisationIdTests.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Register/Query/RegisterQuerySearchForStandardsTests.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/RegisterUpdate/RegisterUpdateTestsBase.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/RegisterUpdate/WhenRegisterUpdateCalled_AndEPAOIsMissing.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/RegisterUpdate/WhenRegisterUpdateCalled_AndEPAONameIsDifferent.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/RegisterUpdate/WhenRegisterUpdateCalled_AndItReturnsAPreviouslyDeletedEPAO.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/RegisterUpdate/WhenRegisterUpdateCalled_AndItReturnsUnknownEpao.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/RegisterUpdate/WhenRegisterUpdateCalled_AndUkPrnIsDifferent.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/RegisterUpdate/WhenRegisterUpdateRequestIsSent.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Search/SearchHandlerTestBase.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Search/When_returned_learners_do_not_match_users_epaorgid.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Search/When_returned_learners_match_users_epaorgid.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Certificates/Batch/CreateBatchCertificateHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/RegisterUpdate/RegisterUpdateHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/RegisterUpdate/RegisterUpdateRequest.cs
  src/SFA.DAS.AssessorService.Application/Handlers/RegisterUpdate/RegisterUpdateResponse.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Search/SearchResultExtensions.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Staff/StaffSearchHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Staff/StartCertificateHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/ao/GetOrganisationStandardHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/ao/GetStandardsByAssessmentOrganisationHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/ao/SearchStandardsHandler.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/IEpaOrganisationValidator.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/IStandardService.cs
  src/SFA.DAS.AssessorService.Data/RegisterQueryRepository.cs
  src/SFA.DAS.AssessorService.EpaoImporter/EpaoImporterFunction.cs
  src/SFA.DAS.AssessorService.ExternalApis/AssessmentOrgs/AssessmentOrgsApiClient.cs
  src/SFA.DAS.AssessorService.ExternalApis/AssessmentOrgs/IAssessmentOrgsApiClient.cs
  src/SFA.DAS.AssessorService.Web.Staff.Tests/Controllers/PrivateCertificateTests/Posts/CertificatePostBase.cs
  src/SFA.DAS.AssessorService.Web.Staff.Tests/Controllers/PrivateCertificateTests/Queries/CertificateQueryBase.cs
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/Private/CertificatePrivateStandardCodeController.cs
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/RegisterController.cs
  src/SFA.DAS.AssessorService.Web.Staff/Infrastructure/ApiClient.cs
  src/SFA.DAS.AssessorService.Web.Staff/Infrastructure/IApiClient.cs
  src/SFA.DAS.AssessorService.Web.Staff/Models/SearchStandardsViewModel.cs
  src/SFA.DAS.AssessorService.Web.Staff/Views/Register/EditOrganisation.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Register/SearchStandardsResults.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Register/ViewOrganisation.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/appsettings.Development.json
  src/SFA.DAS.AssessorService.Web.UnitTests/PrivateCertificateTests/Posts/CertificatePostBase.cs
  src/SFA.DAS.AssessorService.Web/Controllers/Private/CertificatePrivateStandardCodeController.cs
Labels: Tested

#732 ON-1848 Changes to Manage Users page
  src/SFA.DAS.AssessorService.Web.UnitTests/ManageUsersTests/InviteUserControllerTests/When_Invite_is_called.cs
  src/SFA.DAS.AssessorService.Web.UnitTests/ManageUsersTests/ManagerUsersControllerTests/When_User_is_called.cs
  src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/InviteUserController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/ManageUsersController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/UserDetailsController.cs
  src/SFA.DAS.AssessorService.Web/Views/ManageUsers/Index.cshtml
Labels: Manage Users

#729 APR-393 google analytics added
  src/SFA.DAS.AssessorService.Web.Staff/Views/Shared/_Layout.cshtml
Labels: RoATP

#741 ON-1887 - Re-Synchronise Staff auth roles on Dashboard & Controllers
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/CertificateApprovalsController.cs
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/Roatp/RoatpHomeController.cs
  src/SFA.DAS.AssessorService.Web.Staff/Views/Dashboard/Index.cshtml
Labels: Tested

#737 ON-1812 Update Register With New Given name and Family name
  src/SFA.DAS.AssessorService.Data/RegisterRepository.cs
  src/SFA.DAS.AssessorService.Web.Staff/Services/AnswerInjectionService.cs
Labels: Tested

#722 Apr 292 update company number
  src/SFA.DAS.AssessorService.Api.Types/Models/Roatp/UpdateOrganisationCompanyNumberRequest.cs
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/Roatp/UpdateRoatpOrganisationController.cs
  src/SFA.DAS.AssessorService.Web.Staff/Infrastructure/IRoatpApiClient.cs
  src/SFA.DAS.AssessorService.Web.Staff/Infrastructure/RoatpApiClient.cs
  src/SFA.DAS.AssessorService.Web.Staff/Validators/Roatp/IUpdateOrganisationCompanyNumberValidator.cs
  src/SFA.DAS.AssessorService.Web.Staff/Validators/Roatp/UpdateOrganisationCompanyNumberValidator.cs
  src/SFA.DAS.AssessorService.Web.Staff/Validators/Roatp/UpdateOrganisationCompanyNumberViewModelValidator.cs
  src/SFA.DAS.AssessorService.Web.Staff/ViewModels/Roatp/UpdateOrganisationCompanyNumberViewModel.cs
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/SearchResults.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/UpdateOrganisationCompanyNumber.cshtml
Labels: RoATP, Tested

#725 Apr 293 update charity number
  src/SFA.DAS.AssessorService.Api.Types/Models/Roatp/UpdateOrganisationCharityNumberRequest.cs
  src/SFA.DAS.AssessorService.Application.Api/Resources/Validators/EpaOrganisationValidator.en.resx
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/Roatp/UpdateRoatpOrganisationController.cs
  src/SFA.DAS.AssessorService.Web.Staff/Infrastructure/IRoatpApiClient.cs
  src/SFA.DAS.AssessorService.Web.Staff/Infrastructure/RoatpApiClient.cs
  src/SFA.DAS.AssessorService.Web.Staff/Resources/RoatpOrganisationValidation.Designer.cs
  src/SFA.DAS.AssessorService.Web.Staff/Resources/RoatpOrganisationValidation.resx
  src/SFA.DAS.AssessorService.Web.Staff/Validators/Roatp/IUpdateOrganisationCharityNumberValidator.cs
  src/SFA.DAS.AssessorService.Web.Staff/Validators/Roatp/UpdateOrganisationCharityNumberValidator.cs
  src/SFA.DAS.AssessorService.Web.Staff/Validators/Roatp/UpdateOrganisationCharityNumberViewModelValidator.cs
  src/SFA.DAS.AssessorService.Web.Staff/ViewModels/Roatp/UpdateOrganisationCharityNumberViewModel.cs
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/SearchResults.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/Roatp/UpdateOrganisationCharityNumber.cshtml
Labels: RoATP, Tested

#728 ON-1873 - Upsert security headers
  src/SFA.DAS.AssessorService.Application.Api/StartupConfiguration/SecurityHeadersExtensions.cs
  src/SFA.DAS.AssessorService.Web.Extensions/SecurityHeadersExtensions.cs
Labels: Requires testing

#743 On 1881 use of json to submit data
  src/SFA.DAS.AssessorService.Web.Staff.Tests/Controllers/PrivateCertificateTests/Queries/Given_I_request_the_approvals._page .cs
  src/SFA.DAS.AssessorService.Web.Staff.Tests/MockedObjects/MockedApiClient.cs
  src/SFA.DAS.AssessorService.Web.Staff/Controllers/CertificateApprovalsController.cs
  src/SFA.DAS.AssessorService.Web.Staff/ViewModels/Private/CertificateApprovalPostViewModel.cs
  src/SFA.DAS.AssessorService.Web.Staff/ViewModels/Private/CertificateApprovalViewModel.cs
  src/SFA.DAS.AssessorService.Web.Staff/Views/CertificateApprovals/New.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/CertificateApprovals/SentForApproval.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/Views/CertificateApprovals/_ApprovalsScriptsPartial.cshtml
  src/SFA.DAS.AssessorService.Web.Staff/wwwroot/js/epao-validation.js
Labels: Tested

#733 On 1871 using same uln diff lastname
  src/SFA.DAS.AssessorService.Api.Types/Models/SearchResult.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Private/StartPrivateCertificateHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Search/SearchHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Search/SearchResultExtensions.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/ICertificateRepository.cs
  src/SFA.DAS.AssessorService.Data/CertificateRepository.cs
  src/SFA.DAS.AssessorService.Web.Staff/Views/Search/Results.cshtml
  src/SFA.DAS.AssessorService.Web/Controllers/SearchController.cs
  src/SFA.DAS.AssessorService.Web/Orchestrators/Search/SearchOrchestrator.cs
  src/SFA.DAS.AssessorService.Web/ViewModels/Search/ResultViewModel.cs
  src/SFA.DAS.AssessorService.Web/ViewModels/Search/SearchRequestViewModel.cs
  src/SFA.DAS.AssessorService.Web/Views/Search/Result.cshtml
Labels: Tested

#742 On 1872 options page after standards page
  src/SFA.DAS.AssessorService.Web.UnitTests/PrivateCertificateTests/Posts/Given_I_post_the_standard_code_page.cs
  src/SFA.DAS.AssessorService.Web.UnitTests/PrivateCertificateTests/Posts/Given_I_post_the_ukprn_page.cs
  src/SFA.DAS.AssessorService.Web/Controllers/CertificateDeclarationController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/CertificateGradeController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/CertificateOptionController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/Private/CertificatePrivateProviderUkprnController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/Private/CertificatePrivateStandardCodeController.cs
  src/SFA.DAS.AssessorService.Web/Views/Certificate/Date.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Certificate/FirstName.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Certificate/Grade.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Certificate/LearnerStartDate.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Certificate/Option.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Certificate/PrivateDeclaration.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Certificate/StandardCode.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Certificate/Ukprn.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Certificate/Uln.cshtml
Labels: Tested

#754 On 1728 fixes for css upgrade
  src/SFA.DAS.AssessorService.Web/Views/Certificate/Date.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Certificate/LearnerStartDate.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Certificate/StandardCode.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Certificate/_StandardCodesScriptsPartial.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Shared/_DashboardLayout.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Shared/_Layout.cshtml
  src/SFA.DAS.AssessorService.Web/wwwroot/stylesheets/accessible-autocomplete.min.css
  src/SFA.DAS.AssessorService.Web/wwwroot/stylesheets/application.css
Labels: Tested

#751 ON-1826 When organisation is created in the Staff App required mandatory organisation to be entered; when previously added organisation is loaded display Not set for missing organisation type.
  src/SFA.DAS.AssessorService.Application.Api.UnitTests/Validators/Register/EpaOrganisationValidatorTests.cs
  src/SFA.DAS.AssessorService.Application.Api/Validators/EpaOrganisationValidator.cs
  src/SFA.DAS.AssessorService.Domain/Entities/Organisation.cs
Labels: Tested

#736 ON-1874 Standards shown on the standards tab in the dashboard are effective in future or today
  src/SFA.DAS.AssessorService.Database/StoredProcedures/EPAO_Registered_Standards.sql
Labels: Tested

#755 ON-1909 The EPAO register report will now list all organisations for a standard
  src/SFA.DAS.AssessorService.Database/StoredProcedures/EPAO_Register_list_of_standards.sql
Labels: Tested

#757 ON-1639 - Update title & link to Completed Assessements
  src/SFA.DAS.AssessorService.Web.Staff/Views/Apply/Financial/Graded.cshtml
Labels: Tested

#758 ON-1914 Updated to fix IE issue.
  src/SFA.DAS.AssessorService.Web.Staff/Views/CertificateApprovals/_ApprovalsScriptsPartial.cshtml
  src/SFA.DAS.AssessorService.Web/wwwroot/stylesheets/application.min.css
Labels: Tested
