Repository SkillsFundingAgency/das-assessor-service, pull requests merged in 2021-03, with the labels that each got.

#1117 FAT2-413 - Correct mapping from outer api
  src/SFA.DAS.AssessorService.Application.Api/Services/StandardService.cs
  src/SFA.DAS.AssessorService.Application/Infrastructure/OuterApi/GetStandardsListResponse.cs
Labels: Requires testing

#1115 SV-417 - declaration content
  src/SFA.DAS.AssessorService.Web/Resources/Views/Certificate/Declaration.resx
  src/SFA.DAS.AssessorService.Web/Resources/Views/Certificate/PrivateDeclaration.resx
  src/SFA.DAS.AssessorService.Web/Views/Certificate/Declaration.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Certificate/PrivateDeclaration.cshtml
  src/SFA.DAS.AssessorService.Web/Views/Organisation/OrganisationDetails.cshtml
Labels: EPAO App, External API, Requires testing

#1122 FAT2-438 Provider not found bug
  src/SFA.DAS.AssessorService.Application/Handlers/Certificates/GetCertificatesHistoryHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Certificates/GetCertificatesToBeApprovedHandler.cs
  src/SFA.DAS.AssessorService.Web/Validators/CertificateUkprnViewModelValidator.cs
Labels: Requires testing

#1116 CON-3139 Correctly identify initial applications distinct from financial health checks
  src/SFA.DAS.AssessorService.Api.Types/Models/Apply/ApplicationResponse.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/ApplicationApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/IApplicationApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api/Controllers/Apply/ApplicationController.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Applications/GetApplicationHandlerTests/When_combinded_applications_are_requested.cs
  src/SFA.DAS.AssessorService.Application.UnitTests/Mapping/CustomResolvers/ApplicationTypeResolverTests/When_application_type_is_resolved.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Apply/CreateApplicationHandler.cs
  src/SFA.DAS.AssessorService.Application/Handlers/Apply/GetApplicationsHandler.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/IApplyRepository.cs
  src/SFA.DAS.AssessorService.Application/Mapping/CustomResolvers/ApplicationTypeResolver.cs
  src/SFA.DAS.AssessorService.Data/Apply/ApplyRepository.cs
  src/SFA.DAS.AssessorService.Domain/Consts/ApplicationTypes.cs
  src/SFA.DAS.AssessorService.Web.UnitTests/ApplyControllerTests/ApplicationService/When_BuildInitialRequest_is_called.cs
  src/SFA.DAS.AssessorService.Web/Controllers/Apply/ApplicationController.cs
  src/SFA.DAS.AssessorService.Web/Controllers/Apply/ApplicationService.cs
  src/SFA.DAS.AssessorService.Web/Controllers/Apply/IApplicationService.cs
  src/SFA.DAS.AssessorService.Web/Controllers/Apply/StandardController.cs
Labels: Tested

#1112 CON-3045 Clear batch number correctly on certificate update
  src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/BatchLogs/UpdateBatchLogReadyToPrintAddCertificatesHandlerTests/When_called_to_add_certificates_to_batch.cs
  src/SFA.DAS.AssessorService.Application/Handlers/BatchLogs/UpdateBatchLogReadyToPrintAddCertificatesHandler.cs
  src/SFA.DAS.AssessorService.Application/Interfaces/ICertificateBatchLogRepository.cs
  src/SFA.DAS.AssessorService.Data/CertificateBatchLogRepository.cs
  src/SFA.DAS.AssessorService.Data/CertificateRepository.cs
Labels: Tested
